-- =============================================================================
-- CUPAI — Vision-based internal product descriptions + chat attachments.
--
-- Adds:
--  1. staging_products / products: internal_description (+ hash, status,
--     updated_at) and visual_features jsonb, populated by AI vision the
--     moment product images are uploaded (before approval). Used ONLY
--     internally for smart dedupe/matching — never shown to customers.
--  2. On approval: fields are copied from staging_products -> products
--     inside approve_product_row so the approved product keeps its
--     description. On "skip", staging_products row (and its description)
--     is discarded exactly as today (nothing to change).
--  3. messages.attachments jsonb[] for customer<->agent media (images,
--     videos, files) shared during the chat.
--
-- Safe to re-run. Requires: staging_products, products, messages tables
-- (created in earlier out-of-repo baseline migrations).
-- =============================================================================
BEGIN;

-- 1. staging_products: vision fields (generated ON UPLOAD, before approval).
alter table public.staging_products
  add column if not exists internal_description        text,
  add column if not exists internal_description_hash   text,
  add column if not exists internal_description_status text
      check (internal_description_status in
        ('pending','generating','ready','failed','stale')),
  add column if not exists internal_description_updated_at timestamptz,
  add column if not exists visual_features             jsonb;

alter table public.staging_products
  alter column internal_description_status set default 'pending';

create index if not exists staging_products_desc_status_idx
  on public.staging_products (user_id, internal_description_status);

comment on column public.staging_products.internal_description is
  'INTERNAL only. Deep visual description generated by AI from the product images the moment they are staged. Used for dedupe / merge / matching decisions. Never shown to customers. Discarded automatically when the staging row is skipped.';
comment on column public.staging_products.internal_description_hash is
  'Stable hash of the ordered image set the description was generated from. Regenerate only when this hash changes.';
comment on column public.staging_products.visual_features is
  'Structured breakdown of the visual analysis (colors, materials, patterns, silhouette, distinguishing details). Companion to internal_description; used for scored matching.';

-- 2. products: same vision fields, populated from staging on approval.
alter table public.products
  add column if not exists internal_description        text,
  add column if not exists internal_description_hash   text,
  add column if not exists internal_description_status text
      check (internal_description_status in
        ('pending','generating','ready','failed','stale')),
  add column if not exists internal_description_updated_at timestamptz,
  add column if not exists visual_features             jsonb;

alter table public.products
  alter column internal_description_status set default 'pending';

create index if not exists products_desc_status_idx
  on public.products (user_id, internal_description_status);

comment on column public.products.internal_description is
  'INTERNAL only. Deep visual description of this approved product, carried over from staging_products on approval and refreshed whenever product images change. Used for smart matching of customer-sent images. Never shown to customers.';

-- 3. messages.attachments — media shared in chat by customer OR agent.
-- Each element:
--   { "kind": "image"|"video"|"file",
--     "url": text,           -- signed or public URL
--     "storage_path": text,  -- bucket/object path (nullable for external)
--     "mime": text,
--     "name": text,          -- optional display name
--     "size": int,           -- bytes, optional
--     "source": "customer"|"agent",
--     "product_id": uuid|null, -- when agent sent a product asset
--     "meta": object|null }
alter table public.messages
  add column if not exists attachments jsonb not null default '[]'::jsonb;

comment on column public.messages.attachments is
  'Array of media attached to this message (images/videos/files) — sent either by the customer or by the agent (product assets from the merchant knowledge base).';

-- 4. Update approve_product_row so approved products persist the vision
-- fields already computed on the staging row. Non-breaking: signature and
-- caller unchanged; the RPC reads staging_products in-place.
CREATE OR REPLACE FUNCTION public.approve_product_row(
  p_user_id        uuid,
  p_staging_id     uuid,
  p_fingerprint    uuid,
  p_target_id      uuid,
  p_batch_id       uuid,
  p_product        jsonb,
  p_image_urls     jsonb,
  p_replace_images boolean,
  p_variants       jsonb,
  p_colors         jsonb,
  p_sizes          jsonb
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_id           uuid;
  v_desc         text;
  v_desc_hash    text;
  v_desc_status  text;
  v_desc_updated timestamptz;
  v_features     jsonb;
BEGIN
  -- Pull the AI vision payload from the staging row (may be null if not
  -- yet generated; that's fine — the row will stay 'pending' and the
  -- background worker will fill it in later against the products table).
  SELECT internal_description,
         internal_description_hash,
         internal_description_status,
         internal_description_updated_at,
         visual_features
    INTO v_desc, v_desc_hash, v_desc_status, v_desc_updated, v_features
    FROM staging_products
   WHERE id = p_staging_id AND user_id = p_user_id;

  IF p_target_id IS NULL THEN
    INSERT INTO products (
      user_id, batch_id, name, description, category, price, currency,
      variants, images, is_published, published_at,
      internal_description, internal_description_hash,
      internal_description_status, internal_description_updated_at,
      visual_features
    ) VALUES (
      p_user_id,
      p_batch_id,
      p_product->>'name',
      p_product->>'description',
      p_product->>'category',
      NULLIF(p_product->>'price','')::numeric,
      p_product->>'currency',
      COALESCE(p_product->'variants','[]'::jsonb),
      COALESCE(p_product->'images','[]'::jsonb),
      COALESCE((p_product->>'is_published')::boolean, false),
      NULLIF(p_product->>'published_at','')::timestamptz,
      v_desc, v_desc_hash,
      COALESCE(v_desc_status, 'pending'),
      v_desc_updated,
      v_features
    )
    RETURNING id INTO v_id;
  ELSE
    UPDATE products SET
      name         = CASE WHEN p_product ? 'name'         THEN p_product->>'name'         ELSE name         END,
      description  = CASE WHEN p_product ? 'description'  THEN p_product->>'description'  ELSE description  END,
      category     = CASE WHEN p_product ? 'category'     THEN p_product->>'category'     ELSE category     END,
      price        = CASE WHEN p_product ? 'price'        THEN NULLIF(p_product->>'price','')::numeric ELSE price END,
      currency     = CASE WHEN p_product ? 'currency'     THEN p_product->>'currency'     ELSE currency     END,
      variants     = CASE WHEN p_product ? 'variants'     THEN COALESCE(p_product->'variants','[]'::jsonb) ELSE variants END,
      images       = CASE WHEN p_product ? 'images'       THEN COALESCE(p_product->'images','[]'::jsonb)   ELSE images   END,
      is_published = CASE WHEN p_product ? 'is_published' THEN (p_product->>'is_published')::boolean       ELSE is_published END,
      published_at = CASE WHEN p_product ? 'published_at' THEN NULLIF(p_product->>'published_at','')::timestamptz ELSE published_at END,
      -- Vision fields: only overwrite when staging actually produced them,
      -- so an incremental UPDATE that carries no images doesn't wipe
      -- previously-computed descriptions.
      internal_description             = COALESCE(v_desc,         internal_description),
      internal_description_hash        = COALESCE(v_desc_hash,    internal_description_hash),
      internal_description_status      = COALESCE(v_desc_status,  internal_description_status),
      internal_description_updated_at  = COALESCE(v_desc_updated, internal_description_updated_at),
      visual_features                  = COALESCE(v_features,     visual_features),
      updated_at   = now()
    WHERE id = p_target_id AND user_id = p_user_id
    RETURNING id INTO v_id;
    IF v_id IS NULL THEN
      RAISE EXCEPTION 'Product % not found for user %', p_target_id, p_user_id;
    END IF;

    -- If images changed on this update, mark description stale so the
    -- background worker regenerates against the new image set.
    IF p_replace_images THEN
      UPDATE products
         SET internal_description_status = 'stale'
       WHERE id = v_id AND user_id = p_user_id;
    END IF;
  END IF;

  DELETE FROM product_variants WHERE product_id = v_id;
  IF jsonb_typeof(p_variants) = 'array' AND jsonb_array_length(p_variants) > 0 THEN
    INSERT INTO product_variants (product_id, color, size, price, stock, position)
    SELECT v_id,
           NULLIF(v->>'color',''),
           NULLIF(v->>'size',''),
           NULLIF(v->>'price','')::numeric,
           NULLIF(v->>'stock','')::int,
           COALESCE(NULLIF(v->>'position','')::int, 0)
      FROM jsonb_array_elements(p_variants) AS v;
  END IF;

  IF p_replace_images THEN
    DELETE FROM product_images WHERE product_id = v_id;
    IF jsonb_typeof(p_image_urls) = 'array' AND jsonb_array_length(p_image_urls) > 0 THEN
      INSERT INTO product_images (product_id, user_id, url, position)
      SELECT v_id, p_user_id, elem, (ord - 1)::int
        FROM jsonb_array_elements_text(p_image_urls) WITH ORDINALITY AS t(elem, ord);
    END IF;
  END IF;

  IF p_colors IS NOT NULL AND jsonb_typeof(p_colors) = 'array' THEN
    DELETE FROM product_colors WHERE product_id = v_id;
    IF jsonb_array_length(p_colors) > 0 THEN
      INSERT INTO product_colors (product_id, user_id, label, hex, position)
      SELECT v_id, p_user_id,
             c->>'label',
             NULLIF(c->>'hex',''),
             COALESCE(NULLIF(c->>'position','')::int, 0)
        FROM jsonb_array_elements(p_colors) AS c
       WHERE c ? 'label' AND (c->>'label') <> '';
    END IF;
  END IF;

  IF p_sizes IS NOT NULL AND jsonb_typeof(p_sizes) = 'array' THEN
    DELETE FROM product_sizes WHERE product_id = v_id;
    IF jsonb_array_length(p_sizes) > 0 THEN
      INSERT INTO product_sizes (product_id, user_id, label, position)
      SELECT v_id, p_user_id,
             s->>'label',
             COALESCE(NULLIF(s->>'position','')::int, 0)
        FROM jsonb_array_elements(p_sizes) AS s
       WHERE s ? 'label' AND (s->>'label') <> '';
    END IF;
  END IF;

  UPDATE staging_products SET
    status = 'approved',
    processing_fingerprint = p_fingerprint,
    failure_reason = NULL,
    failed_at = NULL
  WHERE id = p_staging_id AND user_id = p_user_id;

  RETURN v_id;
END $$;

GRANT EXECUTE ON FUNCTION public.approve_product_row(
  uuid, uuid, uuid, uuid, uuid, jsonb, jsonb, boolean, jsonb, jsonb, jsonb
) TO service_role;

-- 5. Storage bucket for chat attachments. Private; served via signed URLs.
insert into storage.buckets (id, name, public)
values ('chat-attachments', 'chat-attachments', false)
on conflict (id) do nothing;

-- Merchants (authenticated) can read/write their own conversation folders.
-- Folder convention: <merchant_user_id>/<conversation_id>/<uuid>.<ext>
drop policy if exists chat_attachments_owner_rw on storage.objects;
create policy chat_attachments_owner_rw on storage.objects
  for all to authenticated
  using (
    bucket_id = 'chat-attachments'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'chat-attachments'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- service_role bypasses RLS; server code uploads/reads via signed URLs.

COMMIT;
