-- =============================================================================
-- CUPAI — Per-image internal visual description.
--
-- Today `internal_description` + `visual_features` live on products /
-- staging_products and describe the product as a whole. This migration adds
-- the same idea at the individual image level:
--
--  1. product_images: gains `internal_description` (text) and
--     `visual_features` (jsonb) — the deep visual description and structured
--     visual breakdown for THIS specific image, generated by AI vision.
--     Used internally only (dedupe / matching); never shown to customers.
--
--  2. staging_products: gains `image_internal_descriptions` (jsonb, default
--     '[]') — a temporary per-image payload held during the review stage.
--     Each element: { "image_id": ..., "internal_description": ...,
--     "visual_features": {...} }. On approval, the server copies these onto
--     the matching product_images rows; on skip, the staging row (and this
--     column) is discarded exactly like the existing vision fields.
--
-- Safe to re-run.
-- =============================================================================
BEGIN;

-- 1. product_images: per-image vision fields.
alter table public.product_images
  add column if not exists internal_description text,
  add column if not exists visual_features      jsonb;

comment on column public.product_images.internal_description is
  'INTERNAL only. Deep visual description generated by AI vision for THIS specific image (not the product as a whole). Used for dedupe / merge / matching decisions against customer-sent images. Never shown to customers.';
comment on column public.product_images.visual_features is
  'Structured breakdown of the visual analysis for THIS specific image (colors, materials, patterns, silhouette, distinguishing details). Companion to internal_description; used for scored matching.';

-- 2. staging_products: temporary per-image descriptions held until approval.
alter table public.staging_products
  add column if not exists image_internal_descriptions jsonb not null default '[]'::jsonb;

comment on column public.staging_products.image_internal_descriptions is
  'Temporary per-image vision payload held only during the review stage. Array of { image_id, internal_description, visual_features } — one entry per image attached to this staging row. On approval, entries are copied onto the corresponding product_images rows; on skip, this column is discarded together with the staging row. Never shown to customers.';

COMMIT;
